import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Topo from '../componentes/Topo'
import Inicio from '../componentes/Inicio'
import Projetos from '../componentes/Projetos'
import Tecnologias from '../componentes/Tecnologias'
import Informacoes from '../componentes/Informacoes'
import Footer from '../componentes/Rodape'



export default function Home() {
  return (
    <>
      <Head>
        <title>Janser Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
       <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <main className={styles.container}>
        <Topo />
        <Inicio id="inicio"/>
        <Projetos id="projetos"/>
        <Tecnologias id="tecnologias"/>
        <Informacoes id="contato"/>
        <Footer />
        
      </main>
    </>
  )
}
